#!/usr/bin/env bash

set -euo pipefail

# If we're running in CI we need to disable TTY allocation for docker-compose
# commands that enable it by default, such as exec and run.
TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

function rmcontainer {
  docker rm -vf $(docker ps -aq)
}

function rmimage {
  # docker rmi $(docker images -q -f dangling=true)
  docker rmi -f $(docker images -aq)
}

function build {
  docker build . -t "${@}"
}

function run {
  docker run --rm -p 3000:3000 -d --name petshop "${@}"
}

function stopp {
  docker stop "${@}"
  docker rm -f "${@}"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
